### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by xmha97** [Yet-Zio/yetCalc#120]
Hi, please support the Android 13 themed app icon feature.

![Screenshot_2024-04-01-03-18-52-689_de.mm20.launcher2.release.jpg](https://github.com/Yet-Zio/yetCalc/assets/23485114/c281d56a-969b-4026-b615-79abd1cbb1da)

Thanks for developing this app.

**Comment by Yet-Zio** [comment]
@xmha97 ofcourse, its in the works, It will be present in the new update:

![monochromeyetcalc](https://github.com/Yet-Zio/yetCalc/assets/38321498/e45a684e-c984-4104-b5b6-c784922b1c1a)

**Comment by Yet-Zio** [comment]
Added as of #122
