### ISSUE TITLE
Converter - 1 feet is not 11.99939 inches

### ISSUE THREAD

**Issue by slmb3** [Yet-Zio/yetCalc#13]
Converting 1 feet to inches returns 11.999390429747026.

similarly, converting 12 inches to feet returns 1.0000508001016004.

default settings on v1.0.3

**Comment by Yet-Zio** [comment]
Hello @slmb3, thanks for noting that out. There were some approximations made for some units. Such as when converting from feet to inch or vice versa, it first converts to metre then to rest. 

Some approximations tend to have been wrong, I will look into this once I get enough time and hopefully release a fix.

**Comment by Yet-Zio** [comment]
@slmb3 The issue has been fixed as of #25
