### ISSUE TITLE
Inches(in) to Feet(ft) Convertor doesn't work

### ISSUE THREAD

**Issue by abishekmuthian** [Yet-Zio/yetCalc#137]
Thank you for your work with yetCalc, excellent application.

Inches(in) to Feet(ft) Convertor doesn't work where as Feet to Inches works.

![Screenshot_20240531-094223_yetCalc](https://github.com/Yet-Zio/yetCalc/assets/51737091/d2936528-c325-4ff8-9766-067a7aed5dc0)

**Comment by Yet-Zio** [comment]
Hello @abishekmuthian, thanks for the report. However, Im not experiencing the same issue:

![Screenshot_20240531-111258](https://github.com/Yet-Zio/yetCalc/assets/38321498/7ee7ed9b-c3c1-4d23-93b3-b740f024d8d4)

Could you please check if the version of yetCalc you are using is 1.1.4

**Comment by Yet-Zio** [comment]
@abishekmuthian Is your issue resolved?

**Comment by abishekmuthian** [comment]
Hi, I checked the F-Droid and the version I was using was the latest `1.1.4` and when I launched through it the error didn't occur. I couldn't reproduce it.

Sorry for the trouble.  I will close the issue.
