### ISSUE TITLE
remember last used converter / unit

### ISSUE THREAD

**Issue by asklow** [Yet-Zio/yetCalc#14]
Remember last used converter section as well as it's units of possible.

Motivation: I mostly use one specific converter more than others, so I had hard time always switching back to it, caz the app won't remember & resets me back to the default first one (currency).

**Comment by Yet-Zio** [comment]
Sorry for that, probably in the upcoming updates I will make it so that the converter remembers it.

**Comment by Yet-Zio** [comment]
Hi @asklow the new release [v1.0.4](https://github.com/Yet-Zio/yetCalc/releases/tag/1.0.4) provides the feature to remember the last used section/tab like you asked. However, units are not remembered due to some spinner(combobox/unit selector) issues.

Added as of #17
