### ISSUE TITLE
Rounding and precision settings don't work

### ISSUE THREAD

**Issue by BadIDMan** [Yet-Zio/yetCalc#140]
![Screenshot_20240925_064239_yetCalc](https://github.com/user-attachments/assets/2de48ffa-39ff-41f9-894f-bd789315b7cc)

Whatever settings I set:
Left Justify Results on/off
Almost Integer Rounding on/off
Canonical Rounding on/off

its always result as on attached screenshot.

**Comment by Yet-Zio** [comment]
Hi @BadIDMan, Left justify result is for aligning result(text) to left not the numbers.

You need to set Canonical Rounding to on like this:
![Screenshot_20240925-144230](https://github.com/user-attachments/assets/93114bd5-4d1e-486d-9a36-d067eadd5c83)

Then the result would be:
![Screenshot_20240925-144046](https://github.com/user-attachments/assets/1103aba4-ef8a-4b8b-8488-7222b7751b5e)

**Comment by BadIDMan** [comment]
With these 3 settings set to "on" result of multiplying these numbers is indeed OK.
I played with these 3 settings but omitted 3 of them to set to "on" :-)
I'm using version 1.1.4

**Comment by Yet-Zio** [comment]
Yea, the settings are sometimes confusing 😅
Glad to know the issue is resolved. Thank You.
