### ISSUE TITLE
Reproducible build failed

### ISSUE THREAD

**Issue by IzzySoft** [Yet-Zio/yetCalc#151]
For v2.0.0, RB failed. Reason is a timestamp inserted by aboutLibraries. APK diff:

```diff
  -rw----     0.0 fat      684 b-      364 defN 1981-01-01 01:01:02 53c6e500 res/M5.xml
- -rw----     0.0 fat    63931 b-     9403 defN 1981-01-01 01:01:02 023e7a83 res/M7.json
+ -rw----     0.0 fat    63931 b-     9405 defN 1981-01-01 01:01:02 3f501275 res/M7.json
  -rw----     0.0 fat     1196 b-      397 defN 1981-01-01 01:01:02 0db276ad res/M7.xml
```

`M7.json` start:

```yaml
{"metadata":{"generated":"2024-11-26T10:10:14.642Z"},"libraries":
```

As that timestamp is generated at build time, the app cannot be RB as the timestamps will always differ. Solution: Add the following to your `app/build.gradle.kts`:

```kotlin
aboutLibraries {
    // Remove the "generated" timestamp to allow for reproducible builds
    excludeFields = arrayOf("generated")
}
```

Thanks in advance!

(PS: this means v2.0.0 won't reach F-Droid.org as their RB will fail, too. At IzzyOnDroid, v2.0.0 will show up in about half an hour, but indicate a failed RB. You might wish to make a "maintenance release" including the above fix, e.g. v2.0.1, to get the update to F-Droid.)

**Comment by Yet-Zio** [comment]
Thanks for reviewing that @IzzySoft.
I will release a build right away.

**Comment by Yet-Zio** [comment]
Done as of #152

**Comment by IzzySoft** [comment]
_:notes: … I'm a trigger hippie … :notes:_

(_triggers update_ success _triggers build_ success _triggers repo update_ oops)

Confirming RB. Reporting:

    ! repo/yetzio.yetcalc_17.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

Easy to avoid with another minor adjustment in your `build.gradle.kts`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Oops, another one:

    yetzio.yetcalc: 17.txt for en-US has 672 chars

Please see the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for limits in Fastlane metadata:

* per-release changelogs: max 500 chars each
* short description: max 80 chars
* full description: max 4000 chars (consider that converting it to HTML increases the number of characters, so try keeping it below 3.500 chars)

Graphics have their own specification, all outlined in the docs (including some hints on formatting  Co).

No rush, if the next release (whenever it is ready) has that fixed, that would be nice. Thanks!

:crossed_fingers:

**Comment by Yet-Zio** [comment]
😂man not again, Sheesh google and their weird changes. Well then, I gotta release a build too. Hope no issue arises again.

**Comment by Yet-Zio** [comment]
_🎶 … New release published with the changes … 🎶_

Hope everything works 😅

**Comment by IzzySoft** [comment]
Eh, I said "no rush" – this was nothing *that* urgent, could have waited a few days. But thanks!

Btw: that "weird change" rolled out last year. I usually tell devs whenever I have to report something else anyway; guess half of the apps at IoD have that BLOB removed meanwhile. A few months ago, F-Droid picked up as well and asks for removing it when you want to add an app there (RFP) – though to my knowledge they do not yet scan it for existing apps on updates (they had to reach out to a lot of devs then, hard to catch up – which is why at IoD, we do that "alongside other reports" for now, hopefully solving it slowly but steadily).

You want me to pick up your new release right now (to see if everything's fine) – or is it OK to wait for the next automated run in about 18h from now? In the latter case, be welcome to give me a ping in about 20+h from know so I don't forget to tell you the results (after checking the logs).

**Comment by IzzySoft** [comment]
No red alert --. but machine room, bring the **green** shield up :stuck_out_tongue_winking_eye: Sync hopefully within the next half hour, RB succeeded already.
