### ISSUE TITLE
operation error

### ISSUE THREAD

**Issue by acopernic** [Yet-Zio/yetCalc#16]
Example
1*2=2
Multiply the result (2) using the *
It appears on the left.. Then you cannot do any calculation with more than one step

**Comment by Yet-Zio** [comment]
Ah, seems like fixing support for real numbers caused this issue. You can still compute afterwards, its just that the cursor is placed at front. Hopefully I will release a fix today. Thanks for your report.

**Comment by Yet-Zio** [comment]
Issue has been fixed as of #17
