### ISSUE TITLE
negative temperature celsius

### ISSUE THREAD

**Issue by trend-1** [Yet-Zio/yetCalc#19]
Hi,

I'm trying to convert -4 °C to Fahrenheit.  
But it doesn't seem possible to input a negative number.

What to do now?

**Comment by Yet-Zio** [comment]
@trend-1 Sorry for the inconvenience, I didn't test out every unit. Enforcing only positive numbers seems to be a issue with the fragment view since I used numberDecimal for all tabs. This will be fixed in the next update. Again, thank you for your report.

**Comment by trend-1** [comment]
👍

**Comment by Yet-Zio** [comment]
@trend-1 The issue has been fixed as of #25
