### ISSUE TITLE
Programmer mode - divide by 0 crashes the app.

### ISSUE THREAD

**Issue by JamieDoesStuff** [Yet-Zio/yetCalc#20]
The title of the issue, pretty much. Happens with all numeral systems.

**Comment by Yet-Zio** [comment]
@JamieDoesStuff thanks for reporting that. Seems like it does crash, I will probably release a fix for that soon.

**Comment by Yet-Zio** [comment]
@JamieDoesStuff The issue has been fixed as of #25
