### ISSUE TITLE
Perfect circles

### ISSUE THREAD

**Issue by tvnmguy** [Yet-Zio/yetCalc#23]
![IMG_20230112_072351.jpg](https://user-images.githubusercontent.com/116799295/211957412-72879825-ce8b-432f-847b-6a28f00f2804.jpg)

These aren't perfect circles, oval shaped

**Comment by Yet-Zio** [comment]
@tvnmguy, Yes this is an evident issue since the buttons might differ on taller phones and even on the average ones (not a perfect circle), this happens probably due to the drawables used without same width and height. Thanks for your report and I will probably fix this in the upcoming updates.

**Comment by Yet-Zio** [comment]
Fixed with new major version upgrade #147
