### ISSUE TITLE
Remove existing tab from selection menu

### ISSUE THREAD

**Issue by tvnmguy** [Yet-Zio/yetCalc#26]
![IMG_20230114_095316.jpg](https://user-images.githubusercontent.com/116799295/212450472-2eec9457-9c2d-4b3d-88b6-2dff3bd2a038.jpg)
![IMG_20230114_095238.jpg](https://user-images.githubusercontent.com/116799295/212450476-38421e9f-d0a5-45ec-b43d-3fd702076d78.jpg)
![IMG_20230114_095207.jpg](https://user-images.githubusercontent.com/116799295/212450487-ca4a68b2-3ca5-4626-b2d9-ce02bf058c50.jpg)

★But retain current tab's title

![IMG_20230114_095716.jpg](https://user-images.githubusercontent.com/116799295/212450564-d0974b36-dc90-49ed-8ef8-c5947813e1d5.jpg)

**Comment by Yet-Zio** [comment]
@tvnmguy that's a nice suggestion, would make the selection list much smaller as well. I will look into it.

**Comment by Yet-Zio** [comment]
Done as of #147
