### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Yet-Zio/yetCalc#30]
https://monitor.f-droid.org/builds/log/yetzio.yetcalc/6#site-footer

Could you please take a look?

**Comment by Yet-Zio** [comment]
@linsui Seems like its not reproducible again. I applied the fix you mentioned in this update to [app/build.gradle](https://github.com/Yet-Zio/yetCalc/blob/main/app/build.gradle). What could be the issue?

**Comment by Yet-Zio** [comment]
I checked if there's any missing changes with WinMerge but it shows only difference in only carriage return types.

![Screenshot 2023-01-15 175954](https://user-images.githubusercontent.com/38321498/212540650-2856c823-4182-4d84-a30e-c0b64bdcb812.jpg)

Could this be the issue?

**Comment by Yet-Zio** [comment]
I did a clean rebuild, here's the log:
[logyetcalc.txt](https://github.com/Yet-Zio/yetCalc/files/10420239/logyetcalc.txt)

Should I reupload the build?

**Comment by linsui** [comment]
Yes, please. You can unzip the apk and check if the asset folder exists. Thanks!

**Comment by Yet-Zio** [comment]
Hello @linsui, the asset folder appears to be missing.

**Comment by linsui** [comment]
Then please upload it and the reproducible build should works in the next build cycle. Thanks!
