### ISSUE TITLE
Result overlapping menubar on Fairphone 3plus

### ISSUE THREAD

**Issue by Hackbroetchen** [Yet-Zio/yetCalc#32]
![Screenshot_20230127-103445_yetCalc](https://user-images.githubusercontent.com/75432809/215055050-1aa0c2a0-fa24-43c8-84f6-51e7944ef290.png)
This calculator is all I was looking for except this tiny flaw. <3

**Comment by Yet-Zio** [comment]
Hey @Hackbroetchen , thanks for reporting that. It might be due to the screen size or a weird padding issue, I will check if that's the case. Let me know if you any other issues.

**Comment by Yet-Zio** [comment]
@Hackbroetchen I tested it on a Pixel 3 that has a lower screen size than yours. Your fairphone 3plus by specification appears to be 5.65 with a resolution of 1080 x 2160. The Pixel 3 has the same, although I can't reproduce the issue there:

![Screenshot_20230127_161314_framed](https://user-images.githubusercontent.com/38321498/215068082-14fd1431-b4ff-464d-8d6e-c24efcaafabb.png)

**Comment by Yet-Zio** [comment]
@Hackbroetchen Can you specify your phone size and resolution? Or is this page right: [Fairphone 3+ Specs](https://www.gsmarena.com/fairphone_3+-10069.php)

**Comment by Hackbroetchen** [comment]
That is correct. Thank you for the quick reaction.
I installed /e/os (1.6-r-20221129238947-stable-FP3) that is android 11. Maybe that has to do with that. Maybe someone else that has the same issue and can share his phone specs.

**Comment by Yet-Zio** [comment]
Thanks for the update, seems like a layout issue or something associated with the rom. Could you test this apk and let me know if that fixed it:

https://www.mediafire.com/file/u8j203f341y9dfs/yetCalcLytTest.apk/file

**Comment by Hackbroetchen** [comment]
Changes nothing.
But I experimented  a bit and found out that when I decrease the display size option from "default" to "small" the issue goes away.
![Screenshot_20230129-115415_Settings](https://user-images.githubusercontent.com/75432809/215321382-fefc8ed0-74c2-4611-9c7d-59df5a799869.png)
Although it squiched the buttons a bit:
![Screenshot_20230129-114833_yetCalc](https://user-images.githubusercontent.com/75432809/215321538-0c23969f-9805-49ca-9da4-413aa2b49645.png)
This might be a way to reproduce the issue on your device because setting screen size to "large" worsens it.

Turning on gesture navigation solves it as well.

**Comment by Yet-Zio** [comment]
That's how the buttons should actually look tho. Seems setting small resolves most issues for you. When I first tested on pixel 3, it was on default and had no problems. The issue does occur when the size is large, larger. I have a doubt here as well about your display size, it seems to have 5 options for the slider but small is at the middle and as per your response default should be higher. This means there's large which is at the last. However, what about the options at leftmost, is it like smaller, smallest? Your display setting being "small" appears as default to me considering your screen size.

Anyway, thanks for the report.
