### ISSUE TITLE
Programmer mode - operation sign disappear when number system changed

### ISSUE THREAD

**Issue by Baton34** [Yet-Zio/yetCalc#35]
Example:
- in Programmer mode choose HEX
- enter '10', enter '+'
- in history string shows '010 +'
- change number system to DEC
- in history string shows '16' without operation sign
- enter '1'
- in history string shows '161'
- press '='
- in history string shows '17'
So when number system changed during formula entering, operation sign is disappear.
This is very confusing.

**Comment by Yet-Zio** [comment]
@Baton34 , thanks for the report. It is as you said, the operation remains but the operator becomes invisible in history string. Might be because I toggled some things when the result was empty. Will look into this once I get time.

**Comment by Yet-Zio** [comment]
Fixed as of #44
