### ISSUE TITLE
Bubnoff units are completely off

### ISSUE THREAD

**Issue by Eiim** [Yet-Zio/yetCalc#36]
Bubnoff units (speed) convert to about .1c, consistent across various units, when they should be something like a millimeter per year. It seems like this comes from app/src/main/java/yetzio/yetcalc/component/UnitConv.kt, where the formulas in MetreperSecToBubnoff and BubnoffToMetreperSec are swapped.

**Comment by Yet-Zio** [comment]
@Eiim Thanks for reporting that :). Yea it seems like the conversion was wrong for those two methods, now I wonder where I took those conversation rates from. I will probably release a new update within these days.

Sorry for any inconvenience.

**Comment by Yet-Zio** [comment]
Fixed as of #44
