### ISSUE TITLE
long press the delete button to delete all digits

### ISSUE THREAD

**Issue by Wjxfi** [Yet-Zio/yetCalc#38]
this has already been done https://github.com/Darkempire78/OpenCalc , and I find it very convenient (Helps in solving big math examples)

**Comment by Yet-Zio** [comment]
@Wjxfi sure, I will add that in the coming update.

**Comment by praveenrajput** [comment]
@Yet-Zio are you working on this or can I fix it?

**Comment by Yet-Zio** [comment]
@praveenrajput Im having exams, so I didn't start work on it yet. But sure, you can add it! :)

**Comment by Yet-Zio** [comment]
Added and improved as of #44
