### ISSUE TITLE
colors other than green in the dark theme

### ISSUE THREAD

**Issue by Wjxfi** [Yet-Zio/yetCalc#39]
When I'm in a calculator all the time, I get a little tired of the green colors.

I want variety and at least a few new ones

**Comment by Yet-Zio** [comment]
@Wjxfi I can understand your concern with the dark theme, but the color scheme is based on the selected colors I chose when I first created the app, the icon and related resources, quite different from other calcs. But I will ofcourse add new themes in the future related to dark/light with different color schemes.
