### ISSUE TITLE
totally black theme

### ISSUE THREAD

**Issue by Wjxfi** [Yet-Zio/yetCalc#40]
it helps the battery a lot on some types of screens (they just turn off the pixels in completely black places)

https://github.com/Darkempire78/OpenCalc already did that
![312144.jpg](https://user-images.githubusercontent.com/113500363/218330195-a2ef7c6b-b569-4b61-8396-0bfbedfab75c.jpg)

**Comment by Yet-Zio** [comment]
@Wjxfi I understand the situation, its called amoled theme. Some apps provide this such as discord, etc. yetCalc will support this in the future and this feature has been requested before, See: #22
