### ISSUE TITLE
Not all digits are visible in portrait mode

### ISSUE THREAD

**Issue by thomas2403** [Yet-Zio/yetCalc#48]
Not all digits are shown in landscape mode. This is the result of square root 3. The first picture shows the result after calculation. I have scroll manualy to see the first digits (2nd picture). Would it be possible to reduce the number of digits or make the font smaller?

![Screenshot_20230304-184916_yetCalc](https://user-images.githubusercontent.com/17723660/222921320-147c2e03-ae9c-43ae-86f5-38b4dedd918b.png)
![Screenshot_20230304-184953_yetCalc](https://user-images.githubusercontent.com/17723660/222921323-8a8dc94f-4509-4281-a8b5-ced7690754f9.png)

**Comment by Yet-Zio** [comment]
Hmm, I think you meant portrait mode.
There's no problems on landscape mode:
![Screenshot_20230304-234515](https://user-images.githubusercontent.com/38321498/222922255-6e9b6f57-7f02-46e9-94ba-8c63498f95f1.png)

I understand the situation tho, like larger numbers/calculations tend to go beyond the actual screen width and its harder to scroll. 
Yea, I will probably add a setting to adjust the font size. That could resolve the issue :)

**Comment by thomas2403** [comment]
Yes, I meant portrait mode. It would be great, if you could do this.

**Comment by neco154** [comment]
Can you please left align numbers in portrait mode that we can se more importain part of number. Last digits are never so important.

**Comment by CaptainPackers** [comment]
I would like to see a font size option added as well. I also have this problem and I use my phone locked in portrait mode, so it would be convenient to reduce the font size. This is my goto calculator, but this quirk has me thinking about looking for an alternative.

P. S : I love the unit converter. Nice job on that!

**Comment by Yet-Zio** [comment]
Results are left aligned as of v1.1.2 . Can be changed in settings as well. #107 
Issue similar to #51
