### ISSUE TITLE
Material you

### ISSUE THREAD

**Issue by ThatOneCalculator** [Yet-Zio/yetCalc#5]
Support for Material You colors and a generally more MD3 design would be great

**Comment by Yet-Zio** [comment]
Hi @ThatOneCalculator, sure Material Design would really enhance the app feel and look. I will look into it. Thanks for the suggestion.

**Comment by CapoFantasma97** [comment]
Would really be cool, I hope it will get addressed someday

**Comment by Yet-Zio** [comment]
Done with #147
