### ISSUE TITLE
 programmers can't paste 

### ISSUE THREAD

**Issue by off-by-zero-error** [Yet-Zio/yetCalc#55]
hi, i am encountering one simple difficulty with this.  when using the programmer mode, there seems to be no interaction to paste a value from the clipboard contents. 

 in calculater mode there is clearly a flashing bar | to indicate input.  long pressing that area brings the system overlay offering "paste" and an overflow elipsis to reveal "auto-fill" which i guess is redundant for a calculater but who knows. also a backspace ⌫ button is present and functional. 

 back in programmer mode there is no indication of input, there is no response for long press anywhere.  also there is no backspace.  this state persists in landscape orientation. 

 programmers always write values and inputs by hand, and wouldn't make mistakes while doing so, but as a borky scripter i would love to use this tool too.  in any case, thankyou for your time and effort.

**Comment by Yet-Zio** [comment]
Done as of #147
