### ISSUE TITLE
The program does not work with percentages.

### ISSUE THREAD

**Issue by 51522** [Yet-Zio/yetCalc#57]
+/- using the percent symbol does not give correct results.
Try this: 100-13%. The result will be: 99.87

**Comment by Yet-Zio** [comment]
@51522 Please multiply the percent value with the total value. For example: 100-13%*100 will give you desired result. Please refer [Help](https://github.com/Yet-Zio/yetCalc/blob/main/HELP.md) to get a clear idea. Percentages work in a more traditional way. By default percentages are calculated in 1.

**Comment by Yet-Zio** [comment]
Hope this solves the issue

**Comment by 51522** [comment]
Then it is easier to count not as 100-13%*100, but as 100*0.87
Thanks for the clarification!

**Comment by Yet-Zio** [comment]
One more thing I wanted to mention is its not required during division/mutliplication. Some users had confusion over that since different calculators use a different method. Think I will update Help.md as well. Glad to know it helped.
