### ISSUE TITLE
Add units symbols in converter

### ISSUE THREAD

**Issue by fievel** [Yet-Zio/yetCalc#60]
A nice enhancement would be to add standard unit symbols alongside the full name of the unit in the converter.
 
A good start would be to simply add it between parenthesis or brackets in the string describing the units.

**Comment by Yet-Zio** [comment]
Thanks for the idea. I have added the symbols and abbreviations corresponding to the units in the new [update](https://github.com/Yet-Zio/yetCalc/releases/latest).

Added as of #61
