### ISSUE TITLE
Why it isnt on Google Play?

### ISSUE THREAD

**Issue by inson1** [Yet-Zio/yetCalc#66]

**Comment by Yet-Zio** [comment]
@inson1 I do want to, its that I have not setup a google play developer account to publish apps on play store which as far as I know requires a one time $25 fee unlike fdroid which is free.

As soon as I have enough balance left for the one time fee, I will publish the app :).

**Comment by inson1** [comment]
@Yet-Zio Did you publish it? I cant find it.

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
