### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [Yet-Zio/yetCalc#7]
Please add this app to the F-Droid main repository.

**Comment by Yet-Zio** [comment]
Hello @xmha97, the app's metadata is [already merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12346) in the fdroid main data repo. Added it few days back, the app will appear on fdroid shortly.

**Comment by xmha97** [comment]
Thank you, this app is really great, especially the programmer tab.

**Comment by Yet-Zio** [comment]
Glad to hear you like it ;)
