### ISSUE TITLE
Something is up with exchangerate.host

### ISSUE THREAD

**Issue by duvjones** [Yet-Zio/yetCalc#76]
I think that the site is down and with it the API.

**Comment by Yet-Zio** [comment]
Ah, thanks for the report. Yea this seems to be the issue:

![Screenshot 2023-09-22 100716](https://github.com/Yet-Zio/yetCalc/assets/38321498/e1ddce9f-9361-4d02-b488-5c8622400286)

Fortunately, it has already been reported.
![Screenshot 2023-09-22 101028](https://github.com/Yet-Zio/yetCalc/assets/38321498/247af3ee-8ee8-4094-8bb9-359390c13aef)

Let's just wait and hope that the issue will be fixed.

**Comment by Yet-Zio** [comment]
Seems like the issue has been resolved :)
