### ISSUE TITLE
[Feature Request] Add date format options in settings

### ISSUE THREAD

**Issue by inson1** [Yet-Zio/yetCalc#78]
It would be great to set your favorite format.
I like for example DD-MM-YYYY

date format in the history view
date format in the Converter in Currency

Thank you :)

**Comment by Yet-Zio** [comment]
@inson1 By calender format option, I assume you meant the date format in the history view. If so, I will surely add it in the future.

**Comment by inson1** [comment]
@Yet-Zio No I meant in Converter in Currency, but this would be also great!
Should I create second issue? or let this issue be for all date formats?

**Comment by Yet-Zio** [comment]
Added as of #91
