### ISSUE TITLE
System theme

### ISSUE THREAD

**Issue by xmha97** [Yet-Zio/yetCalc#8]
Please add the "System Default" theme and set it as the default theme.

**Comment by Yet-Zio** [comment]
Hey @xmha97, the upcoming updates will provide this feature recognizing system theme. Hope yetCalc serves you well! ;)

**Comment by xmha97** [comment]
Thank you for adding this feature; It is important for me to app follow the operating system theme.

**Comment by jacekpoz** [comment]
hey, what's the status on this?

**Comment by xmha97** [comment]
Thank you 🙏
