### ISSUE TITLE
F-Droid version still on v1.0.9 - Currency Converter Broken

### ISSUE THREAD

**Issue by Blend3rman** [Yet-Zio/yetCalc#86]
The F-droid listing for this app hasn't been updated to v1.1.0 yet. Since the currency converter is broken on the previous version, I'm requesting you update the app on F-Droid repo as well. Grabbing the apk from your GitHub v1.1.0 release for now.

**Comment by Yet-Zio** [comment]
Hello @Blend3rman, as far as I know, the app did update on F-Droid 2 days ago.

I just checked both the website and the app as well, it seems to have updated:

![Screenshot_20231007-150050](https://github.com/Yet-Zio/yetCalc/assets/38321498/d3aac7c5-4da5-461e-be68-c9e9e00dfcf4)

![Screenshot 2023-10-07 150227](https://github.com/Yet-Zio/yetCalc/assets/38321498/0d090978-9656-49f5-b0fe-19ce31c989c8)

Are you sure you updated the F-Droid app repositories?

**Comment by antenore** [comment]
It's updated for me and the currency converter is working.
Maybe @Blend3rman you have networking issues

**Comment by inson1** [comment]
I had same problem, clearing cache and storage solved it.
